# MySQL 연결
spring.datasource.url=jdbc:mysql://localhost:3306/mall_test
spring.datasource.username=mall_test
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 포트 설정 (React 3000, Spring 8080)
server.port=8080


jwt.secret=mallSecretKey123456789012345678901234567890  # 토큰 암호화 키
jwt.expiration=86400000  # 토큰 유효시간 (24시간 = 밀리초)